---
# tasks file for elastalert
- name: Install build dependencies
  package:
    state: present
    name: "{{ item }}"
    use: auto
  become: yes
  with_items:
    - epel-release
    - python34-setuptools
    - python34-devel
    - supervisor
    - git
    - gcc

- name: Install pip
  command: easy_install-3.4 pip
  become: yes
  args:
    creates: /usr/bin/pip3

- name: Create Elastalert directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ home_dir }}"
    - "{{ config_dir }}"
    - "{{ logs_dir }}"
    - "{{ rules_dir }}"
  become: yes

- name: Create Elastalert user
  user:
    name: "{{ user }}"
  become: yes

- name: Clone source code
  git:
    repo: "{{ git_repo }}"
    dest: "{{ source_dir }}"
    version: "{{ version }}"
  notify: "Restart Elastalert"
  become: yes

- name: Install Elastalert requirements
  pip:
    requirements: "{{ source_dir }}/requirements.txt"
  become: yes
  
- name: Template Elastalert config file
  template:
    dest: "{{ config }}"
    src: "elastalert.yaml.j2"
    owner: "{{ user }}"
  notify: "Restart Elastalert"
  become: yes

- name: Template Elastalert start script
  template:
    dest: "{{ start_script }}"
    src: "start-elastalert.sh.j2"
    # owner: "{{ user }}"
    mode: 744 # Allow everyone to WX for user only
  notify: "Restart Elastalert"
  become: yes

- name: Template Superviserd config for Elastalert
  template:
    dest: "{{ supervisor_conf }}"
    src: supervisord.conf.j2
    owner: "{{ user }}"
  notify: "Restart Elastalert"
  become: yes