---
- name: Install vsftpd and ftp
  yum:
    name:
      - vsftpd
      - ftp
    state: present

- name: Install FirewallD
  yum:
    name: firewalld
    state: present

- name: Start and Enable vsftpd
  systemd:
    name: vsftpd
    state: started
    enabled: yes

- name: Start FirewallD
  systemd:
    name: firewalld
    state: started

- firewalld:
    zone: public
    port: 21/tcp
    permanent: yes
    state: enabled

- firewalld:
    service: ftp
    zone: public
    permanent: yes
    state: enabled

- name: firewalld reload
  command: firewall-cmd --reload