---
- name: Include system vars
  include_vars:
    file: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - default.yml
- name: Include package repositories 
  include: o2-package-repos.yml
- name: Include dependencies for development
  include: ossim-package-deps.yml
- name: Include dependencies for development
  include: configure-postgres.yml
- name: include git repos for building
  include: ossim-git-repos.yml
- name: include build scripts
  include: ossim-build.yml
...