---
- name: Copy build scripts
  copy:
    src: build-scripts/
    dest: "{{ destination }}"
    mode: 0774
- name: Copy ossim-preferences
  copy:
    src: ossim-preferences
    dest: "{{ destination }}"
    mode: 0664
- name: Ensure .bash_profile sources our build environment
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    block: |
      . build-env.sh
      . .sdkman/bin/sdkman-init.sh
    marker: '# {mark} ANSIBLE MANAGED BLOCK - build environment'
    insertbefore: BOF
    create: yes
...