system_packages:
  - autotools-dev
  - cmake
  - debhelper
  - git
  - gcc
  - libgeos++-dev
  - libjsoncpp-dev
  - libgeotiff-dev
  - libopenscenegraph-dev
  - libzzip-dev
  - libtiff5-dev
  - libjpeg-dev
  - libexpat1-dev
  - libpng-dev
  - libgif-dev 
  - libgeotiff-dev
  - libopenthreads-dev
  - libfreetype6-dev
  - libtiff-dev
  - postgresql
  - postgis
  - wget
  - zlib1g-dev