---
- name: Store ssh command
  blockinfile:
    # Make sure to set the role_path variable in vars/main.yml
    path: '{{ role_path }}/files/my_ec2_ssh_commands.md'
    marker: ''
    block: |
      instance: {{ item.tags.Name }} - created: {{ ansible_date_time.date }}
      ssh -i {{ key_pair_path }}/{{ key_name }}.pem ami-specific-user@{{ item.public_dns_name }}
    insertafter: EOF
  with_items: '{{ ec2_out.instances }}'
  become: yes
