---
# defaults file for elastalert

index: elastalert_status
git_repo: https://github.com/Yelp/elastalert.git
version: HEAD
config: "{{ config_dir }}/elastalert.yaml"
start_script: "{{ home_dir }}/start-elastalert.sh"
supervisor_conf: /etc/supervisord.conf

home_dir: "/opt/elastalert"
config_dir: "{{ home_dir }}/config"
logs_dir: "{{ home_dir }}/logs"
rules_dir: /opt/rules
source_dir: "{{ home_dir }}/source"

elasticsearch:
  host: localhost
  port: 9200
  cert: /etc/elasticsearch/admin-cert
  key: /etc/elasticsearch/admin-key
